image:
  file: .gitpod.dockerfile
  context: apache
ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
tasks:
  - name: MySQL
    command: >
        mysql
        source sfa-1.5.1.sql
  - name: Apache
    command: >
        apachectl start &&
        multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
  - before: cd site/
